export const fonts = [
  { name: 'Abram', family: 'Abram', cyrillic: 'partial', group: 'Скриншот' },
  { name: 'Anselmo', family: 'Anselmo', cyrillic: true, group: 'Скриншот' },
  { name: 'Benvolio', family: 'Benvolio', cyrillic: 'partial', group: 'Скриншот' },
  { name: 'Capuletty', family: 'Capuletty', cyrillic: 'partial', group: 'Скриншот' },
  { name: 'Djiovanni', family: 'Djiovanni', cyrillic: true, group: 'Скриншот' },
  { name: 'Eskal', family: 'Eskal', cyrillic: 'partial', group: 'Скриншот' },
  { name: 'Gregory', family: 'Gregory', cyrillic: 'partial', group: 'Скриншот' },
  { name: 'Lexa', family: 'Lexa', cyrillic: false, group: 'Скриншот' },
  { name: 'Lorenco', family: 'Lorenco', cyrillic: 'partial', group: 'Скриншот' },
  { name: 'Montekky', family: 'Montekky', cyrillic: 'partial', group: 'Скриншот' },
  { name: 'Pacifico', family: 'Pacifico', cyrillic: true, group: 'Скриншот' },
  { name: 'Pag', family: 'Pag', cyrillic: true, group: 'Скриншот' },
  { name: 'Paris', family: 'Paris', cyrillic: true, group: 'Скриншот' },
  { name: 'Salavat', family: 'Salavat', cyrillic: true, group: 'Скриншот' },
  { name: 'Samson', family: 'Samson', cyrillic: true, group: 'Скриншот' },
  { name: 'Stefano', family: 'Stefano', cyrillic: 'partial', group: 'Скриншот' },
  { name: 'Amatic SC', family: 'AmaticSC', cyrillic: true, group: 'Дополнительные' },
  { name: 'Bad Script', family: 'BadScript', cyrillic: true, group: 'Дополнительные' },
  { name: 'Balsamiq Sans', family: 'BalsamiqSans', cyrillic: true, group: 'Дополнительные' },
  { name: 'Bellota', family: 'Bellota', cyrillic: true, group: 'Дополнительные' },
  { name: 'Caveat', family: 'Caveat', cyrillic: true, group: 'Дополнительные' },
  { name: 'Comforter', family: 'Comforter', cyrillic: true, group: 'Дополнительные' },
  { name: 'Great Vibes', family: 'GreatVibes', cyrillic: true, group: 'Дополнительные' },
  { name: 'Lobster', family: 'Lobster', cyrillic: true, group: 'Дополнительные' },
  { name: 'Marck Script', family: 'MarckScript', cyrillic: true, group: 'Дополнительные' },
  { name: 'Neucha', family: 'Neucha', cyrillic: true, group: 'Дополнительные' },
  { name: 'Pangolin', family: 'Pangolin', cyrillic: true, group: 'Дополнительные' },
  { name: 'Pattaya', family: 'Pattaya', cyrillic: true, group: 'Дополнительные' },
  { name: 'Shantell Sans', family: 'ShantellSans', cyrillic: true, group: 'Дополнительные' },
  { name: 'Sriracha', family: 'Sriracha', cyrillic: false, group: 'Дополнительные' },
  { name: 'Underdog', family: 'Underdog', cyrillic: true, group: 'Дополнительные' },
  { name: 'MewTooHand', family: 'MewTooHand', cyrillic: true, group: 'Рукописные · кириллица' },
  { name: 'Gochi Hand Cyrillic', family: 'GochiHandCyrillic', cyrillic: true, group: 'Рукописные · кириллица' },
  { name: 'Itim Cyrillic', family: 'ItimCyrillic', cyrillic: true, group: 'Рукописные · кириллица' },
  { name: 'Hi Melody Cyrillic', family: 'HiMelodyCyrillic', cyrillic: true, group: 'Рукописные · кириллица' },
  { name: 'East Sea Dokdo Cyrillic', family: 'EastSeaDokdoCyrillic', cyrillic: true, group: 'Рукописные · кириллица' },
  { name: 'Romochka', family: 'Romochka', cyrillic: true, group: 'Рукописные · кириллица' },
  { name: 'Pecita', family: 'Pecita', cyrillic: true, group: 'Рукописные · кириллица' },
  { name: 'Miama Nueva', family: 'MiamaNueva', cyrillic: true, group: 'Рукописные · кириллица' },
  { name: 'Manskribo Sans', family: 'ManskriboSans', cyrillic: true, group: 'Рукописные · кириллица' },
  { name: 'Maksik Hand', family: 'MaksikHand', cyrillic: 'partial', group: 'Рукописные · кириллица' },
]

export const defaultFontPool = fonts.filter((font) => font.cyrillic === true).map((font) => font.family)
